# Builds a development version of the site and publishes it's English version to Github pages.
os: osx
git:
  depth: 1
install:
  - brew update
  - brew install hugo sassc
script: tools/build_dev.sh
deploy:
  - provider: pages
    project-name: https://vibrobox.github.io/preview.com/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    repo: VibroBox/preview.com
    on:
      branch: master
    target-branch: master
    local-dir: public/en
    committer-from-gh: true
  - provider: pages
    project-name: https://vibrobox.github.io/preview.ru/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    repo: VibroBox/preview.ru
    on:
      branch: master
    target-branch: master
    local-dir: public/ru
    committer-from-gh: true
