# Our "build" script also automatically deploys static html sites.
# - Build & deploy do not work for forked pull requests (can't deploy without secure $GITHUB_TOKEN).
# - Build results from pull requests are deployed to dev Github pages.
# - Build results from the master branch are deployed directly into production Github pages.
if: fork = false
language: minimal
git:
  depth: 1
  submodules_depth: 1
install: true
# tools/build.sh is for production, tools/build_dev.sh is for dev testing.
script: if [ "$TRAVIS_BRANCH" == "master" ]; then tools/build.sh; else tools/build_dev.sh; fi
after_success: if [ "$TRAVIS_BRANCH" != "master" ]; then \
                 LOCAL_DIR=public/en REPO_SLUG=biodranik/test TARGET_BRANCH=english tools/deploy.sh \
                 LOCAL_DIR=public/ru REPO_SLUG=biodranik/test FQDN=test.ru TARGET_BRANCH=russian tools/deploy.sh \
               fi
# Deployment sections below push from master branch to production Github Pages.
deploy:
  - provider: pages
    # TODO Change to production
    repo: VibroBox/preview.com
    local-dir: public/en
    project-name: https://vibrobox.github.io/preview.com/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
    target-branch: master
    committer-from-gh: true
  - provider: pages
    # TODO Change to production
    repo: VibroBox/preview.ru
    local-dir: public/ru
    project-name: https://vibrobox.github.io/preview.ru/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
    target-branch: master
    committer-from-gh: true
