# Minimum hugo version required: 0.31

BaseUrl: https://www.vibrobox.com/
DefaultContentLanguage: en
ContentDir: content
PublishDir: docs
StaticDir: static/common

BuildDrafts: true
BuildExpired: true
BuildFuture: true
DefaultContentLanguageInSubdir: false
EnableMissingTranslationPlaceholders: true
MetadataFormat: yaml
DisableKinds: [taxonomy, taxonomyTerm, RSS]
I18nDir: translations
Logi18nwarnings: true

# Urls with year and month for the news section.
# Title or file name will be used if slug is not defined in the post frontmatter.
permalinks:
  news: /news/:year/:month/:slug/

Languages:
  en:
    Weight: 1
    LanguageName: English
    LanguageCode: en
    Title: In English
    GoogleAnalytics: UA-79782596-1
    Copyright: © 2017 VibroBox OÜ
    Description: TODO Default English description
    Keywords: [TODO, default, keywords]
    StaticDir2: static/en
    demourl: https://demo.vibrobox.com/demo?locale=en
  ru:
    BaseUrl: https://www.vibrobox.ru/
    Weight: 2
    LanguageName: Русский
    LanguageCode: ru
    Title: На русском
    GoogleAnalytics: UA-79782596-2
    BlackFriday:
      AngledQuotes: true
    Copyright: © 2017 VibroBox
    Description: TODO Описание страницы на русском по-умолчанию, для всего сайта
    Keywords: [TODO, ключевые, слова, по-умолчанию]
    StaticDir2: static/ru
    demourl: https://demo.vibrobox.com/demo?locale=ru
    # TODO: Uncommend when section localization bug will be fixed (see news/_index.ru.md for details).
    #permalinks:
    #  news: /новости/:year/:month/:slug/
